- params:
    # Git parameters
    git:
      # [Mandatory]
      # Name of the git repository to scan
      repoName: jfrog-github-example

      # [Mandatory]
      # List of branches to scan
      branches:
        - main
    scan:
      includeAllVulnerabilities: true
      failOnSecurityIssues: false
      # projects:
      #   - workingDirs:
      #      - python-example/pip-example
